### PR TITLE
Add user style version

### LINKED ISSUE #30: Add a user style version
Since this is a CSS only solution, I suggest adding a user style version so people like me who don't want to install lots of extensions can use it with a user style manager (like [Stylus](https://github.com/openstyles/stylus)) instead.

There should be a GitHub action to generate an `oldschool-github.user.css` when the style is updated:

```css
/* ==UserStyle==
@name         Old School GitHub
@version      <insert version>
@description  Reverts most of GitHub to its classic look
@license      MIT
@author       daattali
@homepageURL  https://github.com/daattali/oldschool-github-extension
@namespace    daattali
==/UserStyle== */

@-moz-document url-prefix("https://github.com/"), url-prefix("https://gist.github.com/") {
  <insert style>
}
```

### PR DESCRIPTION
**Pull request by kidonng**
Close #30

- Add user style version
- Add a script and GitHub action to generate the user style automatically after changing `osgh.css`

### CODE REVIEW

**Comment by daattali** [comment]
Will I need to explicitly provide a github token to the Github Actions job?

**Comment by kidonng** [comment]
No, it is automatically created, see https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token.

**Comment by daattali** [comment]
Thanks a lot, this is great.

I changed the action to trigger when the manifest is updated so that it only happens when the version is bumped.

Is there a reason you made the version `{version}.0` instead of just `{version}`?

**Comment by kidonng** [comment]
> I changed the action to trigger when the manifest is updated

That makes sense 👍

> Is there a reason you made the version `{version}.0` instead of just `{version}`?

https://github.com/daattali/oldschool-github-extension/blob/master/generate-user-style.js#L6

If the user style doesn't comply with SemVer then it can't be installed.

**Comment by kidonng** [comment]
If the manifest version is following SemVer I think that line can be dropped.

**Comment by daattali** [comment]
Thanks. I'll use semantic versioning more strictly then, and remove the extra `0`

**Review by 89649155050 — COMMENTED** [review]
> []() #

**Comment by 89649155050** [comment]
> #

**Comment by 89649155050** [comment]
#26

**Pull request merged**
