### PR TITLE
Remove rounded edges

### PR DESCRIPTION
**Pull request by InfamousStarFox**
Limited .Box css changes to the .repository-content  class

### CODE REVIEW

**Comment by daattali** [comment]
Thanks for the PR, I was trying to avoid doing any rule on something this general because I don't know all the consequences of it (all the places it's used). Which items exactly does this fix, which boxes?

**Comment by InfamousStarFox** [comment]
Square
Attached is a screenshot of how it would affect the box corners. Let me make a change to limit the scope to just repository-content boxes

**Comment by daattali** [comment]
It looks like this completely removes any roundedness. I used waybackmachine to see how github looked before, and there **was** rounded corners still.

Sorry to be so pedantic, but if we touch the rounded corners, I'd want to make them match the pre-update look to go along with this extension's theme, not do something different :)

**Comment by InfamousStarFox** [comment]
Hmm, I was going off of memory. Looks like the old radius was 3px, and the new radius is 6px

**Comment by daattali** [comment]
I don't think Box-header should have rounded edges on all 4 corners, only the top two. Do you agree?

**Comment by InfamousStarFox** [comment]
Yes, I agree. I have updated the css to match

**Comment by daattali** [comment]
Are all the `!important` absolutely necessary?

**Comment by InfamousStarFox** [comment]
No, not all of them. I have removed the extraneous !important tags now

**Comment by daattali** [comment]
Thanks!

**Comment by daattali** [comment]
@InfamousStarFox I'm going to have to revert the button padding. It causes some issues, and it's going to be extremely difficult to test out all the places buttons are used and fix them all.

For example

image


and

image

and

image

**Pull request merged**
